language: objective-c #语言种类

xcode_project: EmptyIOSProject.xcodeproj # 项目文件相对于.travis.yml文件的路径

xcode_scheme: EmptyIOSProject #你需要集成测试的scheme

before_script: ./scripts/add-key.sh

script: xctool -project EmptyIOSProject.xcodeproj -scheme EmptyIOSProject build
# xcode_sdk: iphonesimulator
